-- Supabase SQL Editor-da ishga tushiring (Run)
-- 1. hero_settings
ALTER TABLE public.hero_settings
ADD COLUMN IF NOT EXISTS title_line1_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS title_line2_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS title_highlight_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS subtitle_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS btn1_text_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS btn2_text_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS trust1_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS trust2_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS trust3_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature1_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature1_desc_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature2_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature2_desc_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature3_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature3_desc_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature4_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS feature4_desc_ru TEXT DEFAULT '';

-- 2. categories_settings
ALTER TABLE public.categories_settings
ADD COLUMN IF NOT EXISTS vet_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_desc_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_btn_text_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_item1_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_item2_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_item3_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_item4_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_item5_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS vet_item6_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_desc_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_btn_text_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_item1_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_item2_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_item3_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_item4_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_item5_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS agro_item6_ru TEXT DEFAULT '';

-- 3. product_categories
ALTER TABLE public.product_categories
ADD COLUMN IF NOT EXISTS name_ru TEXT DEFAULT '';

-- 4. products
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS name_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS description_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS "shortDesc_ru" TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS "activeIngredient_ru" TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS specifications_ru JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "tabContent_ru" JSONB DEFAULT '{}';

-- 5. news
ALTER TABLE public.news
ADD COLUMN IF NOT EXISTS title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS excerpt_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS content_ru TEXT DEFAULT '';

-- 6. contact_info
ALTER TABLE public.contact_info
ADD COLUMN IF NOT EXISTS footer_description_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS topbar_marquee_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS address_line1_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS address_line2_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS work_hours_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS day_off_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS footer_copyright_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS footer_developer_ru TEXT DEFAULT '';

-- 7. about_settings
ALTER TABLE public.about_settings
ADD COLUMN IF NOT EXISTS hero_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS hero_subtitle_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS mission_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS mission_text_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS why_title_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS why_item1_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS why_item2_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS why_item3_ru TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS why_item4_ru TEXT DEFAULT '';
