-- Supabase SQL Editor-da ishga tushiring (Run)
CREATE TABLE IF NOT EXISTS public.about_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hero_title TEXT DEFAULT 'Biz haqimizda',
  hero_subtitle TEXT DEFAULT '"Top Agro Vet" — O''zbekiston qishloq xo''jaligi va veterinariya sohasida ishonchli hamkoringiz.',
  mission_title TEXT DEFAULT 'Bizning missiyamiz',
  mission_text TEXT DEFAULT 'Sog''lom chorva va mo''l hosil yetishtirishda eng ilg''or xorijiy va mahalliy texnologiyalarni yurtimizga olib kirish.',
  why_title TEXT DEFAULT 'Nima uchun bizni tanlashadi?',
  why_item1 TEXT DEFAULT 'Yuqori sifat: Barcha mahsulotlarimiz sertifikatlangan va sinovdan o''tgan.',
  why_item2 TEXT DEFAULT 'Keng assortiment: 100 dan ortiq turdagi veterinariya va agro preparatlar.',
  why_item3 TEXT DEFAULT 'Mutaxassis maslahati: Tajribali agronom va veterinar shifokorlarimiz sizga bepul maslahat beradi.',
  why_item4 TEXT DEFAULT 'Tezkor yetkazib berish: Respublika bo''ylab yetkazib berish xizmati.',
  image_url TEXT DEFAULT '/hero-bg.png',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.about_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on about_settings" ON public.about_settings
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users on about_settings" ON public.about_settings
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users on about_settings" ON public.about_settings
  FOR UPDATE USING (true);

-- Boshlang'ich ma'lumot
INSERT INTO public.about_settings (hero_title) VALUES ('Biz haqimizda');
