-- Supabase SQL Editor-da quyidagi kodni ishga tushiring (Run)

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  "categoryLabel" TEXT,
  "subcategoryLabel" TEXT,
  "activeIngredient" TEXT,
  description TEXT,
  "shortDesc" TEXT,
  price NUMERIC,
  "oldPrice" NUMERIC,
  volumes JSONB,
  "selectedVolume" TEXT,
  "inStock" BOOLEAN DEFAULT true,
  rating NUMERIC DEFAULT 0,
  "reviewCount" INTEGER DEFAULT 0,
  "regNumber" TEXT,
  manufacturer TEXT,
  country TEXT,
  "preparatForm" TEXT,
  classification TEXT,
  "shelfLife" TEXT,
  images JSONB,
  specifications JSONB,
  "tabContent" JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) siyosati
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Barchaga o'qish huquqini berish
CREATE POLICY "Enable read access for all users" ON public.products
  FOR SELECT USING (true);

-- Adminlar uchun yozish/tahrirlash/o'chirish huquqlarini autentifikatsiyadan o'tganlarga berish (yoki moslashtirish mumkin)
CREATE POLICY "Enable all access for authenticated users" ON public.products
  FOR ALL USING (auth.role() = 'authenticated');
