-- ============================================
-- Kategoriyalar bo'limi sozlamalari jadvali
-- Supabase SQL Editor-da ishga tushiring
-- ============================================

CREATE TABLE IF NOT EXISTS public.categories_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Veterinariya kartasi
  vet_title TEXT DEFAULT 'Veterinariya preparatlari',
  vet_desc TEXT DEFAULT 'Hayvonlar salomatligi bizning g''amxo''rligimizda',
  vet_btn_text TEXT DEFAULT 'Katalogni ko''rish',
  vet_btn_link TEXT DEFAULT '/catalog/veterinariya',
  vet_item1 TEXT DEFAULT 'Паразидларга қарши воситалар',
  vet_item2 TEXT DEFAULT 'Антибактериал ва яллиғланишга қарши воситалар',
  vet_item3 TEXT DEFAULT 'Акушерлик-гинекологик воситалар',
  vet_item4 TEXT DEFAULT 'Витамин-минерал воситалар',
  vet_item5 TEXT DEFAULT 'Бошқа фарм-гурухлар ва дезинфекция воситалар',
  vet_item6 TEXT DEFAULT 'Кокцидиозга қарши воситалар',
  -- Agro kartasi
  agro_title TEXT DEFAULT 'Agro preparatlari',
  agro_desc TEXT DEFAULT 'Mo''l hosil va yuqori sifat uchun eng yaxshi yechimlar',
  agro_btn_text TEXT DEFAULT 'Katalogni ko''rish',
  agro_btn_link TEXT DEFAULT '/catalog/agro-preparatlar',
  agro_item1 TEXT DEFAULT 'Инсектоцид',
  agro_item2 TEXT DEFAULT 'Инсектоакарацид',
  agro_item3 TEXT DEFAULT 'Фунгицид',
  agro_item4 TEXT DEFAULT 'Гербицид',
  agro_item5 TEXT DEFAULT 'Микроэлементлар',
  agro_item6 TEXT DEFAULT 'Barchasi',
  --
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS siyosati
ALTER TABLE public.categories_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on categories_settings" ON public.categories_settings
  FOR SELECT USING (true);

CREATE POLICY "Enable update for all users on categories_settings" ON public.categories_settings
  FOR UPDATE USING (true);

CREATE POLICY "Enable insert for all users on categories_settings" ON public.categories_settings
  FOR INSERT WITH CHECK (true);

-- Boshlang'ich ma'lumotlarni kiritish
INSERT INTO public.categories_settings (
  vet_title, vet_desc, vet_btn_text, vet_btn_link,
  vet_item1, vet_item2, vet_item3, vet_item4, vet_item5, vet_item6,
  agro_title, agro_desc, agro_btn_text, agro_btn_link,
  agro_item1, agro_item2, agro_item3, agro_item4, agro_item5, agro_item6
) VALUES (
  'Veterinariya preparatlari',
  'Hayvonlar salomatligi bizning g''amxo''rligimizda',
  'Katalogni ko''rish',
  '/catalog/veterinariya',
  'Паразидларга қарши воситалар',
  'Антибактериал ва яллиғланишга қарши воситалар',
  'Акушерлик-гинекологик воситалар',
  'Витамин-минерал воситалар',
  'Бошқа фарм-гурухлар ва дезинфекция воситалар',
  'Кокцидиозга қарши воситалар',
  'Agro preparatlari',
  'Mo''l hosil va yuqori sifat uchun eng yaxshi yechimlar',
  'Katalogni ko''rish',
  '/catalog/agro-preparatlar',
  'Инсектоцид',
  'Инсектоакарацид',
  'Фунгицид',
  'Гербицид',
  'Микроэлементлар',
  'Barchasi'
);
