-- Supabase SQL Editor-da quyidagi kodni ishga tushiring (Run)

CREATE TABLE IF NOT EXISTS public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  image_url TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) siyosati
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- Barchaga o'qish huquqini berish
CREATE POLICY "Enable read access for all users on news" ON public.news
  FOR SELECT USING (true);

-- Barchaga (yoki adminlarga) yozish/tahrirlash huquqlarini berish
CREATE POLICY "Enable insert for all users on news" ON public.news
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users on news" ON public.news
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users on news" ON public.news
  FOR DELETE USING (true);
