-- ============================================
-- Hero bo'limi sozlamalari jadvali
-- Supabase SQL Editor-da ishga tushiring
-- ============================================

CREATE TABLE IF NOT EXISTS public.hero_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_line1 TEXT DEFAULT 'Sog''lom hayvonlar',
  title_line2 TEXT DEFAULT 'va mo''l hosil uchun',
  title_highlight TEXT DEFAULT 'ishonchli tanlov!',
  subtitle TEXT DEFAULT 'Veterinariya va agro preparatlarining keng assortimenti faqat Top Agro Vet''da.',
  btn1_text TEXT DEFAULT 'Veterinariya mahsulotlari',
  btn1_link TEXT DEFAULT '/catalog/veterinariya',
  btn2_text TEXT DEFAULT 'Agro preparatlar',
  btn2_link TEXT DEFAULT '/catalog/agro-preparatlar',
  trust1 TEXT DEFAULT '100% original mahsulotlar',
  trust2 TEXT DEFAULT 'Sertifikatlangan sifat',
  trust3 TEXT DEFAULT 'Mutaxasis yordami',
  -- Features Bar ustunlari
  feature1_title TEXT DEFAULT 'Keng assortiment',
  feature1_desc TEXT DEFAULT '1000+ mahsulot',
  feature2_title TEXT DEFAULT 'Ishonchli brendlar',
  feature2_desc TEXT DEFAULT 'Dunyo bo''ylab ishlab chiqaruvchilar',
  feature3_title TEXT DEFAULT 'Tez yetkazib berish',
  feature3_desc TEXT DEFAULT 'O''zbekistonda barcha viloyatlarga',
  feature4_title TEXT DEFAULT 'Mutaxassis konsultatsiyasi',
  feature4_desc TEXT DEFAULT 'Veterinar va agronomlar yordami',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS siyosati
ALTER TABLE public.hero_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on hero_settings" ON public.hero_settings
  FOR SELECT USING (true);

CREATE POLICY "Enable update for all users on hero_settings" ON public.hero_settings
  FOR UPDATE USING (true);

CREATE POLICY "Enable insert for all users on hero_settings" ON public.hero_settings
  FOR INSERT WITH CHECK (true);

-- Boshlang'ich ma'lumotlarni kiritish
INSERT INTO public.hero_settings (
  title_line1, title_line2, title_highlight,
  subtitle,
  btn1_text, btn1_link, btn2_text, btn2_link,
  trust1, trust2, trust3,
  feature1_title, feature1_desc,
  feature2_title, feature2_desc,
  feature3_title, feature3_desc,
  feature4_title, feature4_desc
) VALUES (
  'Sog''lom hayvonlar',
  'va mo''l hosil uchun',
  'ishonchli tanlov!',
  'Veterinariya va agro preparatlarining keng assortimenti faqat Top Agro Vet''da.',
  'Veterinariya mahsulotlari',
  '/catalog/veterinariya',
  'Agro preparatlar',
  '/catalog/agro-preparatlar',
  '100% original mahsulotlar',
  'Sertifikatlangan sifat',
  'Mutaxasis yordami',
  'Keng assortiment',
  '1000+ mahsulot',
  'Ishonchli brendlar',
  'Dunyo bo''ylab ishlab chiqaruvchilar',
  'Tez yetkazib berish',
  'O''zbekistonda barcha viloyatlarga',
  'Mutaxassis konsultatsiyasi',
  'Veterinar va agronomlar yordami'
);
