-- Supabase SQL Editor-da quyidagi kodni ishga tushiring (Run)

-- 1. Aloqa ma'lumotlari jadvali (telefon, email, manzil, ish vaqti, xarita)
CREATE TABLE IF NOT EXISTS public.contact_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone1 TEXT DEFAULT '',
  phone2 TEXT DEFAULT '',
  email1 TEXT DEFAULT '',
  email2 TEXT DEFAULT '',
  address_line1 TEXT DEFAULT '',
  address_line2 TEXT DEFAULT '',
  work_hours TEXT DEFAULT '',
  day_off TEXT DEFAULT '',
  map_embed_url TEXT DEFAULT '',
  -- Footer ustunlari
  footer_description TEXT DEFAULT '',
  social_telegram TEXT DEFAULT '',
  social_youtube TEXT DEFAULT '',
  social_instagram TEXT DEFAULT '',
  footer_copyright TEXT DEFAULT '',
  footer_developer TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS siyosati
ALTER TABLE public.contact_info ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on contact_info" ON public.contact_info
  FOR SELECT USING (true);

CREATE POLICY "Enable update for all users on contact_info" ON public.contact_info
  FOR UPDATE USING (true);

CREATE POLICY "Enable insert for all users on contact_info" ON public.contact_info
  FOR INSERT WITH CHECK (true);

-- 2. Boshlang'ich ma'lumotlarni kiritish
INSERT INTO public.contact_info (
  phone1, phone2, email1, email2,
  address_line1, address_line2,
  work_hours, day_off, map_embed_url,
  footer_description, social_telegram, social_youtube, social_instagram,
  footer_copyright, footer_developer
) VALUES (
  '+998 90 123 45 67',
  '+998 71 123 45 67',
  'info@topagrovet.uz',
  'support@topagrovet.uz',
  'Toshkent shahri, Chilonzor tumani,',
  'Bunyodkor shoh ko''chasi, 42-uy',
  'Dushanba - Shanba: 08:00 - 18:00',
  'Yakshanba: Dam olish kuni',
  'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2998.073069253112!2d69.2043005!3d41.2855141!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8ba578f4f58d%3A0xd7a2ecf23413b7a0!2sBunyodkor%20Shoh%20Ko''chasi%2C%20Tashkent%2C%20Uzbekistan!5e0!3m2!1sen!2s!4v1700000000000!5m2!1sen!2s',
  'O''zbekistonda veterinariya va agro preparatlarning ishonchli yetkazib beruvchisi. 1000+ dan ortiq mahsulot, sertifikatlangan sifat va mutaxassis maslahatlar.',
  'https://t.me/topagrovet',
  'https://youtube.com/@topagrovet',
  'https://instagram.com/topagrovet',
  '© 2026 Top Agro Vet. Barcha huquqlar himoyalangan.',
  'Sayt Dream Tech IT agency tomonidan ishlab chiqilgan'
);

-- 3. Xabar yuborish jadvali (formadan kelgan xabarlar)
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on contact_messages" ON public.contact_messages
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users on contact_messages" ON public.contact_messages
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users on contact_messages" ON public.contact_messages
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users on contact_messages" ON public.contact_messages
  FOR DELETE USING (true);
