-- ============================================
-- Mahsulotlar uchun dinamik katalog va sub-kataloglar jadvali
-- ============================================

CREATE TABLE IF NOT EXISTS public.product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES public.product_categories(id) ON DELETE CASCADE,
  icon TEXT,
  type TEXT, -- masalan 'veterinariya', 'agro' kabi asosiy bo'limlarga ajratish uchun
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS siyosati
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on product_categories" ON public.product_categories
  FOR SELECT USING (true);

CREATE POLICY "Enable all for authenticated users on product_categories" ON public.product_categories
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Boshlang'ich asosiy kataloglarni qo'shish
INSERT INTO public.product_categories (name, slug, parent_id, icon, type) VALUES
('Veterinariya preparatlari', 'veterinariya', null, 'shield', 'veterinariya'),
('Agro preparatlar', 'agro-preparatlar', null, 'leaf', 'agro');

-- Boshlang'ich sub-kataloglarni qo'shish (ixtiyoriy)
-- Veterinariya (id=1) uchun:
INSERT INTO public.product_categories (name, slug, parent_id, icon, type) VALUES
('Parazitlarga qarshi vositalar', 'parazitlarga-qarshi-vositalar', 1, 'bug', 'veterinariya'),
('Antibakterial va yallig''lanishga qarshi vositalar', 'antibakterial-va-yalliglanishga-qarshi-vositalar', 1, 'pill', 'veterinariya'),
('Akusherlik-ginekologik vositalar', 'akusherlik-ginekologik-vositalar', 1, 'heart', 'veterinariya');

-- Agro (id=2) uchun:
INSERT INTO public.product_categories (name, slug, parent_id, icon, type) VALUES
('Insektotsid', 'insektotsid', 2, 'bug', 'agro'),
('Fungitsid', 'fungitsid', 2, 'leaf', 'agro'),
('Gerbitsid', 'gerbitsid', 2, 'sprout', 'agro');
